export const ATTENDANCE_REQUEST = 'ATTENDANCE_REQUEST';
export const ATTENDANCE_SUCCESS = 'ATTENDANCE_SUCCESS';
export const ATTENDANCE_FAIL = 'ATTENDANCE_FAIL';

export const STUDENT_DETAIL_REQUEST = "STUDENT_DETAIL_REQUEST"
export const STUDENT_DETAIL_SUCCESS = "STUDENT_DETAIL_SUCCESS"
export const STUDENT_DETAIL_FAIL = "STUDENT_DETAIL_FAIL"

export const CHECKOUT_UPDATE_REQUEST = "CHECKOUT_UPDATE_REQUEST"
export const CHECKOUT_UPDATE_SUCCESS = "CHECKOUT_UPDATE_SUCESS"
export const CHECKOUT_UPDATE_FAIL = "CHECKOUT_UPDATE_FAIL"