# Generated by Django 4.0.1 on 2022-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetracker',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
