# Generated by Django 4.0.1 on 2022-03-24 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendancetracker_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetracker',
            name='barcodeId',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
