# Generated by Django 4.0.1 on 2022-03-24 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_attendancetracker_barcodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetracker',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
